# Generated by Django 5.2.6 on 2025-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=100)),
                ('actor1_name', models.CharField(max_length=100)),
                ('actor2_name', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
            ],
            options={
                'ordering': ['movie_title'],
            },
        ),
    ]
